# Generated by Django 5.1.2 on 2024-10-21 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_address_invoices_order_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='invoices_detail',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='invoices',
        ),
        migrations.RemoveField(
            model_name='invoices_details',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoices_details',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='products',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='orders',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
        migrations.DeleteModel(
            name='Invoices_Details',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Shipper',
        ),
        migrations.DeleteModel(
            name='Order_Details',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
