# Generated by Django 5.1.2 on 2024-10-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_supplier_addresses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=100)),
                ('char_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ManyToManyField(to='api.category'),
        ),
    ]
