# Generated by Django 5.1.2 on 2024-11-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_note_price_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
