# Generated by Django 5.1.2 on 2024-11-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_note_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='paymentmethod',
            field=models.IntegerField(choices=[(1, 'Credit Card'), (2, 'Cash'), (3, 'Debit Card')], default=2),
        ),
        migrations.AlterField(
            model_name='note',
            name='price',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
