# Generated by Django 5.1.2 on 2024-11-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_details_paymentmethod_alter_note_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='paymentmethod',
        ),
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.IntegerField(choices=[(1, 'Credit Card'), (2, 'Cash'), (3, 'Debit Card')], default=2),
        ),
    ]
