# Generated by Django 5.1.2 on 2024-11-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_product_alter_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
