# Generated by Django 5.1.2 on 2024-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_category_cate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='times_bought',
            field=models.IntegerField(default=0),
        ),
    ]
