# Generated by Django 5.1.2 on 2024-11-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_times_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='times_bought',
        ),
    ]
